# Generated by Django 6.0.7 on 2026-07-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_address_remove_profile_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_2',
            new_name='landmark',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='postal_code',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_line_1',
            new_name='street',
        ),
        migrations.AddField(
            model_name='address',
            name='house_no',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
