# Generated by Django 6.0.7 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_address_line_2_address_landmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_subject',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
